/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMdiAlert: typeof import('~icons/mdi/alert')['default']
    IMdiArrowDownDrop: typeof import('~icons/mdi/arrow-down-drop')['default']
    IMdiSearch: typeof import('~icons/mdi/search')['default']
    IMdiVideo: typeof import('~icons/mdi/video')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoData: typeof import('./src/components/VideoData.vue')['default']
  }
}
